<?php

use Illuminate\Database\Seeder;

class CurriculumViteasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        \DB::table('curriculum_viteas')->delete();

        \DB::table('curriculum_viteas')->insert(array (
            0 =>
            array (
                'id' => 2,
                'body' => '<p>BORN 1997, THE NETHERLANDS.<br />CURRENTLY LIVING AND WORKING IN GRONINGEN, THE NETHERLANDS.</p>
<p><strong>EDUCATION</strong></p>
<p>2009 - 2014: HAVO, WINKLER PRINS SECONDARY SCHOOL VEENDAM (2009 - 2012 VWO) , NL<br />2014 - 2018: FINE ART (BA), ACADEMY MINERVA, GRONINGEN, NL<br />2018 - NOW: ART HISTORY (MA), UNIVERSITY OF GRONINGEN, NL<br />2018 - NOW: MASTER/APPRENTICE PROJECT, KUNSTPODIUM T, TILBURG, NL</p>
<p><strong>EXHIBITIONS</strong></p>
<p>COMING UP:</p>
<p>14 - 16 SEPTEMBER 2018: &lsquo;DESTILLAAT&rsquo;, EXTRAPOOL NIJMEGEN, NL<br />13 - 16 SEPTEMBER 2018: \'ART ON PAPER&rsquo;, WESTERGASFABRIEK, AMSTERDAM, NL<br />APRIL/JUNE 2019: &lsquo;ONS GELUK&rsquo;, KUNSTHUIS SECRETARIE , MEPPEL, NL</p>
<p>2018<br />FEBRUARY 2018: &lsquo;ITS NOT ME, IT&rsquo;S YOU&rsquo;, ZUHAUSE, GRONINGEN, NL<br />JUNE 2018: &lsquo;HEADLINERS&rsquo; GRADUATION SHOW, SUIKERUNIE, GRONINGEN, NL<br />SEPTEMBER 2018: &lsquo;ART ON PAPER&rsquo;, WESTERGASFABRIEK, AMSTERDAM, NL<br />SEPTEMBER 2018: &lsquo;DESTILLAAT&rsquo;, EXTRAPOOL, NIJMEGEN, NL</p>
<p>2017<br />MAY 2017: \'LEFTOVERS\', MAYDAYS, OOST/THE GYM GRONINGEN, NL<br />FEBRUARI 2017: \'JANUARY EXPO\', ACADEMY MINERVA GRONINGEN, NL</p>
<p>2016<br />OCTOBER 2016: \'WP 150\', VAN BERENSTEYN, VEENDAM, NL<br />SEPTEMBER 2016: THE STUDIOS, GRONINGER MUSEUM, GRONINGEN, NL<br />APRIL 2016: \'DE NIEUWELINGEN\', GALERIE DE SMEDERIJ, SAPPEMEER, NL<br />FEBRUARI 2016: \'ART 15/20\', STICHTING WEP, GRONINGEN, NL</p>
<p>2015<br />JUNE 2015: KUNSTBENDE FINALS, WESTERGASFABRIEK AMSTERDAM, NL</p>
<p>2013<br />AUGUST 2013: KUNSTBENDE FINALS, MELKWEG AMSTERDAM, NL<br />SEPTEMBER 2013: SIMPLON, GRONINGEN, NL</p>
<p><strong>AWARDS</strong></p>
<p>2018<br />NOMINATION KLAAS DIJKSTRAPRIJS, ACADEMY MINERVA, THE NETHERLANDS<br />NOMINATION BLOOOM AWARD, WARSTEINER, GERMANY</p>
<p>2017<br />BEST YOUNG TALENT (GROOTSTE JONG TALENT) NOORDELIJK FILMFESTIVAL, THE NETHERLANDS</p>
<p>2016<br />1TH PLACE KUNSTBENDE NATIONAL (POETRY) , THE NETHERLANDS<br />2TH PLACE KUNSTBENDE NATIONAL (FILM), THE NETHERLANDS</p>
<p><strong>PUBLICATIONS</strong></p>
<p>2018<br />&lsquo;EINDEXAMENEXPOSITIE; MINERVA GRONINGEN&rsquo;, LOST PAINTERS, LOST-PAINTERS.NL<br />&lsquo;GRADUATION SHOW: MINERVA ACADEMY HEADLINERS&rsquo;, MISTER MOTLEY, MISTERMOTLEY.NL<br />ART PRACTICE INTERVIEW WITH ELISA LO AN JOE, SCHOLIEREN.COM</p>
<p>2016<br />&lsquo;DOCUMENT 12&rsquo;, POEM, DE OPTIMIST, ONLINE LITERARY MAGAZINE</p>
<p>2013<br />\'VRUCHTVLEES\', COLLECTION OF POETRY, BOEKSCOUT</p>
<p><strong>PERFORMANCE (TEXTUAL)</strong></p>
<p>2017<br />POEZI&Euml; MET, THEATER DE KAPEL, GRONINGEN, NL<br />DE PO&Euml;ZIEBUS, GROTE MARKT, GRONINGEN NL</p>
<p>2016<br />KUNSTBENDE FINALS, TIVOLI UTRECHT, NL<br />WINTERTUIN FESTIVAL, DOORNROOSJE NIJMEGEN, NL<br />PODIUM NEW ATTRACTION, SPOKEN WORD, SIMPLON GRONINGEN, NL<br />NOISE SOUP &amp; KNOWLEDGE, GALLERY SIGN, (EUROSONIC) GRONINGEN, NL</p>
<p>2015<br />KUNSTBENDE FINALS, WESTERGASFABRIEK AMSTERDAM, NL</p>
<p>2014<br />KUNSTBENDE FINALS, MELKWEG AMSTERDAM, NL</p>
<p>2013<br />KUNSTBENDE FINALS, MELKWEG AMSTERDAM, NL</p>
<p><strong>EXPERIENCE (OTHER)</strong></p>
<p>2018<br />RESIDENCY &lsquo;DESTILLAAT&rsquo;, EXTRAPOOL NIJMEGEN, NL<br />READING: WHY I REFUSE TO PERCEIVE MY RAPIST AS A MONSTER, HARMONIEGEBOUW UNIVERSITEIT GRONINGEN, NL<br />JUDGE FOR KUNSTBENDE PRE-FINALS FILM/EXPO, GRONINGEN, NL</p>
<p>2017<br />MOVIEZONE JURY, IFFR FILMFESTIVAL, ROTTERDAM, NL<br />JURY KUNSTBENDE NATIONAL FINALE (POETRY), TIVOLI UTRECHT, JURY KUNSTBENDE GRONINGEN, SIMPLON (FILM), NL<br />HOSTESS AND TEACHER/INSTRUCTOR, THE STUDIOS, GRONINGER MUSEUM, GRONINGEN, NL</p>
<p>2016<br />YOUNG ARTIST RESIDENCE WEEK , VILLANOVA FESTIVAL + KUNSTBENDE BELGIUM, ANTWERP, BE</p>
<p>2015<br />YOUNG ARTIST EXCHANGE, VILLANOVA FESTIVAL + KUNSTBENDE NL/BE, ANTWERP, BE</p>
<p>&nbsp;</p>'
            ),
        ));


    }
}
